version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0.2-node-browsers
        environment:
          APP_KEY: base64:WIBM5eI11kPy3fwlyTubkHlW+PQyuJXGVuP/F37ZV+I=
          APP_ENV: testing
          DB_HOST: 127.0.0.1
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: user
          DB_PASSWORD: passw0rd

      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo composer self-update
      - restore_cache:
          key: composer-v2-{{ checksum "backend/composer.lock" }}
      - run:
          working_directory: backend
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v2-{{ checksum "backend/composer.lock" }}
          paths:
            - backend/vendor
      - restore_cache:
          key: npm-v2-{{ checksum "backend/package-lock.json" }}
      - run:
          working_directory: backend
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v2-{{ checksum "backend/package-lock.json" }}
          paths:
            - backend/node_modules
      - run:
          working_directory: backend
          command: npm run dev
      - run:
          working_directory: backend
          name: php test
          command: vendor/bin/phpunit
