version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: docker-compose exec app composer install -n --prefer-dist
      - run: docker-compose exec web npm ci
      - run: docker-compose exec web npm run dev
      - run:
          name: php test
          command: docker-compose exec app vendor/bin/phpunit
