version: 2.1
jobs:
  build:
    working_directory: project
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run:
          working_directory: backend
          command: composer install -n --prefer-dist
      - run:
          working_directory: backend
          command: npm ci
      - run:
          working_directory: backend
          command: npm run dev
      - run:
          working_directory: backend
          name: php test
          command: vendor/bin/phpunit
